# @package model.modules.vision_encoder
# Common RGB-pair projection and auxiliary pose supervision.
_recursive_: false
in_chans: 6
img_embed_size: 1024
img_embed_drop: 0.1
pretrained: true
p_drop_prev_img: 0.1
neck_cfg:
  n_res_blocks: 2
  dim: ${model.feat_size}
  dropout: 0.1
loss_pose_weight: 5
heads: {}
