# @package model.modules.vision_encoder
defaults:
  - base
  - _self_
_target_: visnavkit.models.spatial_encoders.vision_encoders.vit_dinov3.DINOv3Encoder
backbone_name: vit_small_patch16_dinov3
freeze_backbone: true
