# @package model.modules.action_decoder.temporal_encoder
embed_dim: ${model.feat_size}
num_heads: 8
num_layers: 1
ff_dim: 2048
seq_len: ${model.export_cfg.seq_len}
dropout: 0.1
reduction: none
mask_p: 0.1
